# coding: utf-8

"""
    Developer API

    API for application developers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_get_user_v1_organizations_org_id_users_user_id_get(self) -> None:
        """Test case for get_user_v1_organizations_org_id_users_user_id_get

        Get User
        """
        pass

    def test_get_user_v1_organizations_org_id_users_user_id_get_0(self) -> None:
        """Test case for get_user_v1_organizations_org_id_users_user_id_get_0

        Get User
        """
        pass

    def test_get_user_v1_organizations_org_id_users_user_id_get_1(self) -> None:
        """Test case for get_user_v1_organizations_org_id_users_user_id_get_1

        Get User
        """
        pass

    def test_get_users_v1_organizations_org_id_users_get(self) -> None:
        """Test case for get_users_v1_organizations_org_id_users_get

        Get Users
        """
        pass

    def test_get_users_v1_organizations_org_id_users_get_0(self) -> None:
        """Test case for get_users_v1_organizations_org_id_users_get_0

        Get Users
        """
        pass

    def test_get_users_v1_organizations_org_id_users_get_1(self) -> None:
        """Test case for get_users_v1_organizations_org_id_users_get_1

        Get Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
