# coding: utf-8

"""
    Developer API

    API for application developers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fast_api_rate_limit_response import FastAPIRateLimitResponse

class TestFastAPIRateLimitResponse(unittest.TestCase):
    """FastAPIRateLimitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FastAPIRateLimitResponse:
        """Test FastAPIRateLimitResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FastAPIRateLimitResponse`
        """
        model = FastAPIRateLimitResponse()
        if include_optional:
            return FastAPIRateLimitResponse(
                detail = 'Rate limit exceeded',
                status_code = 56
            )
        else:
            return FastAPIRateLimitResponse(
        )
        """

    def testFastAPIRateLimitResponse(self):
        """Test FastAPIRateLimitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
