# coding: utf-8

"""
    Developer API

    API for application developers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_organizations_v1_organizations_get(self) -> None:
        """Test case for get_organizations_v1_organizations_get

        Get Organizations
        """
        pass

    def test_get_organizations_v1_organizations_get_0(self) -> None:
        """Test case for get_organizations_v1_organizations_get_0

        Get Organizations
        """
        pass

    def test_get_organizations_v1_organizations_get_1(self) -> None:
        """Test case for get_organizations_v1_organizations_get_1

        Get Organizations
        """
        pass


if __name__ == '__main__':
    unittest.main()
