# coding: utf-8

"""
    Developer API

    API for application developers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.page_user_response import PageUserResponse

class TestPageUserResponse(unittest.TestCase):
    """PageUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageUserResponse:
        """Test PageUserResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageUserResponse`
        """
        model = PageUserResponse()
        if include_optional:
            return PageUserResponse(
                items = [
                    openapi_client.models.user_response.UserResponse(
                        id = 56, 
                        email = '', 
                        github_user_id = '', 
                        github_username = '', 
                        avatar_url = '', 
                        full_name = '', )
                    ],
                total = 56,
                page = 56,
                size = 56,
                pages = 56
            )
        else:
            return PageUserResponse(
                items = [
                    openapi_client.models.user_response.UserResponse(
                        id = 56, 
                        email = '', 
                        github_user_id = '', 
                        github_username = '', 
                        avatar_url = '', 
                        full_name = '', )
                    ],
                total = 56,
                page = 56,
                size = 56,
                pages = 56,
        )
        """

    def testPageUserResponse(self):
        """Test PageUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
