# coding: utf-8

"""
    Developer API

    API for application developers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent_run_v1_organizations_org_id_agent_run_post(self) -> None:
        """Test case for create_agent_run_v1_organizations_org_id_agent_run_post

        Create Agent Run
        """
        pass

    def test_create_agent_run_v1_organizations_org_id_agent_run_post_0(self) -> None:
        """Test case for create_agent_run_v1_organizations_org_id_agent_run_post_0

        Create Agent Run
        """
        pass

    def test_create_agent_run_v1_organizations_org_id_agent_run_post_1(self) -> None:
        """Test case for create_agent_run_v1_organizations_org_id_agent_run_post_1

        Create Agent Run
        """
        pass

    def test_get_agent_run_v1_organizations_org_id_agent_run_agent_run_id_get(self) -> None:
        """Test case for get_agent_run_v1_organizations_org_id_agent_run_agent_run_id_get

        Get Agent Run
        """
        pass

    def test_get_agent_run_v1_organizations_org_id_agent_run_agent_run_id_get_0(self) -> None:
        """Test case for get_agent_run_v1_organizations_org_id_agent_run_agent_run_id_get_0

        Get Agent Run
        """
        pass

    def test_get_agent_run_v1_organizations_org_id_agent_run_agent_run_id_get_1(self) -> None:
        """Test case for get_agent_run_v1_organizations_org_id_agent_run_agent_run_id_get_1

        Get Agent Run
        """
        pass


if __name__ == '__main__':
    unittest.main()
