# coding: utf-8

"""
    Developer API

    API for application developers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.organization_settings import OrganizationSettings

class TestOrganizationSettings(unittest.TestCase):
    """OrganizationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationSettings:
        """Test OrganizationSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationSettings`
        """
        model = OrganizationSettings()
        if include_optional:
            return OrganizationSettings(
                enable_pr_creation = True,
                enable_rules_detection = True
            )
        else:
            return OrganizationSettings(
        )
        """

    def testOrganizationSettings(self):
        """Test OrganizationSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
